VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "box0" do |box0|
    box0.vm.box = "ubuntu/trusty64"
    box0.vm.hostname = "puppetmaster.example.com"
    box0.vm.network "forwarded_port", guest: 443, host: 4443
    box0.vm.network "private_network", ip: "192.168.200.10", adapter: 2
    box0.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file = "master.pp"
    end
  end

  # TODO:
  (1..1).each do |i|
    config.vm.define "box#{i}" do |box|
      box.vm.box = "ubuntu/xenial64"
      box.vm.hostname = "ubuntutest#{i}"
      box.vm.network "forwarded_port", guest: 8080, host: 8080
      box.vm.network "private_network", ip: "192.168.200.#{10 + i}", adapter: 2
      box.vm.provision "shell", inline: "sudo apt-get update && sudo apt-get install -y puppet"
      box.vm.provision "puppet" do |puppet|
        puppet.manifests_path = "manifests"
        puppet.manifest_file = "agent.pp"
      end
    end
  end
end

# vagrant up
